version: 0.1
phases:
  build:
    commands:
      - mvn verify sonar:sonar -Dsonar.projectKey=javaprojectaws -Dsonar.organization=javaprojectaws11 -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=adaa3edca00d0a4255f1cc6e4bb7c2e1c331ab17 
